fix saya uninstall error
GraiaProject/Saya pull request #2
Opened 2021-02-24 08:35 UTC by karakoo

2021-02-24 14:30 UTC, GreyElaina commented
很好 我会在这周五发布包括这个pr的0.0.5

2021-02-24 14:30 UTC, GreyElaina approved these changes

2021-02-25 14:37 UTC, GreyElaina commented
首先 我需要声明 reload后channel实例也被更新了 所以不需要copy detail。。。

2021-02-25 14:38 UTC, GreyElaina commented
哦 也许需要。。。

2021-02-26 09:05 UTC, GreyElaina requested changes

2021-02-26 09:05 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +                exec(f'del channel._py_module.{var_name}')
能不能替换为访问 __dict__ 的形式？

2021-02-26 09:05 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +        self.require(channel.module).copy_details(channel)
我认为这里直接手动 setattr 就好了...

2021-02-26 09:05 UTC, GreyElaina commented on src/graia/saya/channel.py
> +    def copy_details(self, channel: "Channel", ex_list: List[str] = []):
所以这个方法没有必要

2021-02-26 09:28 UTC, karakoo commented on src/graia/saya/__init__.py
> +                exec(f'del channel._py_module.{var_name}')
若要换一种方式的话，就只能像下面这样写了，不过原来的写法更佳简洁一些
```python
for var_name in channel._py_module.__dict__.items():
    if not var_name.startswith('__'):
        exec(f'del channel._py_module.{var_name}')
```

2021-02-26 09:30 UTC, karakoo commented on src/graia/saya/__init__.py
> +        self.require(channel.module).copy_details(channel)
这样？
```python
def reload_channel(self, channel: Channel):
    attr_list = ['_name', '_author', '_description', 'export']
    self.uninstall_channel(channel)
    new_channel = self.require(channel.module)
    for attr in attr_list:
        try:
            new_channel.__setattr__(attr, channel.__getattribute__(attr))
        except AttributeError:
            continue
    return new_channel
```

2021-02-26 09:38 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +                exec(f'del channel._py_module.{var_name}')
我是说
```py
del channel._py_module.__dict__[var_name]
```
类似这样, 但我并不知道 __dict__ 是否可靠.

2021-02-26 09:39 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +                exec(f'del channel._py_module.{var_name}')
..........或者更简单点, 直接 delattr, 或者试试 dict.clear 方法

2021-02-26 09:40 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +        self.require(channel.module).copy_details(channel)
```py
channel._name = new_channel._name
```

类似这样, 这是我的想法

2021-02-26 09:58 UTC, karakoo commented on src/graia/saya/__init__.py
> +        self.require(channel.module).copy_details(channel)
测试了一下，这种写法有效
```python
exec(f'new_channel.{attr} = channel.{attr}')
```

2021-02-26 10:12 UTC, karakoo commented on src/graia/saya/__init__.py
> +        self.require(channel.module).copy_details(channel)
哈哈哈  我自己都笑了  为什么要这么写

2021-02-26 10:15 UTC, karakoo commented on src/graia/saya/__init__.py
> +                exec(f'del channel._py_module.{var_name}')
clear方法有效

2021-02-26 10:20 UTC, GreyElaina commented on src/graia/saya/__init__.py
> +                new_channel.attr = channel.attr
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

2021-02-26 10:20 UTC, merged

2021-02-26 10:21 UTC, GreyElaina commented
我来改.

2021-02-26 10:21 UTC, EricTianC commented on src/graia/saya/__init__.py
> +                new_channel.attr = channel.attr
可还行

2021-02-26 10:22 UTC, EricTianC commented
好耶

2021-02-26 10:29 UTC, karakoo commented on src/graia/saya/__init__.py
> +                new_channel.attr = channel.attr
哈哈哈  傻了